[package]
name = "huffman"
version = "0.1.0"
edition = "2021"
authors = ["Xavier2p <https://github.com/Xavier2p>"]

[dependencies]
clap = { version = "3.2.25", features = ["derive"] }
test-case = "3.1.0"
